name: Run app.py manually

on:
  workflow_dispatch:  # Permite ejecutarlo desde la pestaña "Actions"

jobs:
  run-app:
    runs-on: ubuntu-latest  # Usa una máquina Linux virtual
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run app.py
        run: python app.py
